In [1]:
import keras
keras.__version__


/home/kriti/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


'2.2.2'

## IMDB dataset

In [2]:
from keras.datasets import imdb

In [3]:
(trainX, trainY), (testX, testY) = imdb.load_data(num_words=10000)

In [4]:
trainX.shape

(25000,)

In [5]:
trainY.shape

(25000,)

In [6]:
testX.shape

(25000,)

In [7]:
testY.shape

(25000,)

In [8]:
trainX[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [9]:
trainY[0]

1

In [10]:
max(max(sequence) for sequence in trainX)

9999

## Preparing Data

In [11]:
import numpy as np

def vectorize(x, dimension = 10000):# as we have total 10000 words
    result = np.zeros((len(x), dimension),int)
    
    for (i,x) in enumerate(x):
        result[i,x] = 1
    return result

train_X = vectorize(trainX)
test_X =  vectorize(testX)



        


In [12]:
train_X[0]
#how many words among the whole whole vocabulary is present in the particular sentence holds 1 at that position

array([0, 1, 1, ..., 0, 0, 0])

In [13]:
test_X[0]

array([0, 1, 1, ..., 0, 0, 0])

In [14]:
# as trainX data is in array . so we need to convert  trainY in array.
y_train = np.asarray(trainY).astype('float32')
y_test = np.asarray(testY).astype('float32')

## Model

In [15]:
from keras import models
from keras import layers

In [16]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,))) # 16 is number of hidden units
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [17]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# binary crossentropy because it has binary data

In [18]:
from keras import optimizers

model.compile(optimizer=optimizers.RMSprop(lr=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [19]:
from keras import losses
from keras import metrics

model.compile(optimizer=optimizers.RMSprop(lr=0.001),
              loss=losses.binary_crossentropy,
              metrics=[metrics.binary_accuracy])



In [20]:
x_val = train_X[:10000]
partial_x_train = train_X[10000:]

y_val = y_train[:10000]
partial_y_train = y_train[10000:]

In [21]:
history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_val, y_val))

Train on 15000 samples, validate on 10000 samples
Epoch 1/20
15000/15000 [==============================] - 6s 398us/step - loss: 0.5069 - binary_accuracy: 0.7831 - val_loss: 0.3790 - val_binary_accuracy: 0.8697
Epoch 2/20
15000/15000 [==============================] - 1s 94us/step - loss: 0.3002 - binary_accuracy: 0.9053 - val_loss: 0.3001 - val_binary_accuracy: 0.8903
Epoch 3/20
15000/15000 [==============================] - 2s 127us/step - loss: 0.2179 - binary_accuracy: 0.9282 - val_loss: 0.3083 - val_binary_accuracy: 0.8713
Epoch 4/20
15000/15000 [==============================] - 1s 86us/step - loss: 0.1750 - binary_accuracy: 0.9436 - val_loss: 0.2837 - val_binary_accuracy: 0.8840
Epoch 5/20
15000/15000 [==============================] - 1s 94us/step - loss: 0.1425 - binary_accuracy: 0.9542 - val_loss: 0.2846 - val_binary_accuracy: 0.8863
Epoch 6/20
15000/15000 [==============================] - 1s 96us/step - loss: 0.1150 - binary_accuracy: 0.9649 - val_loss: 0.3139 - val_binary

In [22]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
#model.add(layers.Dense(16, activation= 'relu'))
model.add(layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_X, y_train, epochs=4, batch_size=512)
results = model.evaluate(test_X, y_test)


Epoch 1/4
25000/25000 [==============================] - 2s 83us/step - loss: 0.4749 - acc: 0.8218
Epoch 2/4
25000/25000 [==============================] - 1s 40us/step - loss: 0.2650 - acc: 0.9098
Epoch 3/4
25000/25000 [==============================] - 1s 39us/step - loss: 0.1984 - acc: 0.9301
Epoch 4/4
25000/25000 [==============================] - 2s 92us/step


In [126]:
x=model.predict(test_X)

In [127]:
y = []
for i in x:
    if(i >0.5):
        i=1
        y.append(i)
    else:
        i=0
        y.append(i)
    

In [128]:
y1 = np.asarray(y).astype('int')

In [129]:
y1

array([0, 1, 1, ..., 0, 0, 1])

In [130]:
testY

array([0, 1, 1, ..., 0, 0, 0])

In [131]:
def accuracy(x,y):
    count = 0
    for i in range(0,len(x)):
        if(x[i] == y[i]):
            count = count+1
        
    return (count/len(x))


In [132]:
accuracy(testY,y1)

0.87824